def map_degree(degree_type):
    mapping = {
        'Architecture.': 'Fine Arts',
        'City/Urban, Community and Regional Planning.': 'Sociology',
        'Communication and Media Studies.': 'Communications',
        'Journalism.': 'Communications',
        'Public Relations, Advertising, and Applied Communication.': 'Marketing',
        'Computer Science.': 'Computer Science',
        'Educational Administration and Supervision.': 'General Education',
        'Special Education and Teaching.': 'Elementary Education',
        'Student Counseling and Personnel Services.': 'General Education',
        'Teacher Education and Professional Development, Specific Subject Areas.': 'Elementary Education',
        'Teaching English or French as a Second or Foreign Language.': 'English Language and Literature',
        'Biomedical/Medical Engineering.': 'Biomedical Engineering',
        'Electrical, Electronics and Communications Engineering.': 'Electrical Engineering',
        'Mechanical Engineering.': 'Mechanical Engineering',
        'Industrial Engineering.': 'Mechanical Engineering',
        'Law.': 'Political Science',
        'Legal Professions and Studies, Other.': 'Political Science',
        'Liberal Arts and Sciences, General Studies and Humanities.': 'Liberal Arts',
        'Library Science and Administration.': 'Liberal Arts',
        'Biology, General.': 'Biology',
        'Neurobiology and Neurosciences.': 'Biology',
        'Applied Mathematics.': 'Mathematics',
        'Gerontology.': 'Psychology',
        'Human Biology.': 'Biology',
        'Psychology, General.': 'Psychology',
        'Clinical, Counseling and Applied Psychology.': 'Psychology',
        'Public Administration.': 'Political Science',
        'Public Policy Analysis.': 'Political Science',
        'Social Work.': 'Sociology',
        'Economics.': 'Economics',
        'International Relations and National Security Studies.': 'Political Science',
        'Political Science and Government.': 'Political Science',
        'Sociology.': 'Sociology',
        'Drama/Theatre Arts and Stagecraft.': 'Fine Arts',
        'Film/Video and Photographic Arts.': 'Fine Arts',
        'Fine and Studio Arts.': 'Fine Arts',
        'Music.': 'Fine Arts',
        'Dentistry.': 'Nursing',
        'Dental Support Services and Allied Professions.': 'Nursing',
        'Health and Medical Administrative Services.': 'Nursing',
        'Allied Health Diagnostic, Intervention, and Treatment Professions.': 'Nursing',
        'Medicine.': 'Nursing',
        'Mental and Social Health Services and Allied Professions.': 'Psychology',
        'Pharmacy, Pharmaceutical Sciences, and Administration.': 'Chemistry',
        'Public Health.': 'Nursing',
        'Rehabilitation and Therapeutic Professions.': 'Nursing',
        'Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing.': 'Nursing',
        'Business Administration, Management and Operations.': 'Business Management and Administration',
        'Accounting and Related Services.': 'Accounting',
        'Entrepreneurial and Small Business Operations.': 'Business Management and Administration',
        'Management Sciences and Quantitative Methods.': 'Business Management and Administration',
        'Taxation.': 'Accounting'
    }
    
    return mapping.get(degree_type, 'Unknown')
