version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./src:/main # Optional: For syncing changes during development
    command: gunicorn --bind :8080 --workers 1 --threads 8 main:app
